import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ClerkProvider, auth } from '@clerk/nextjs'
import "./globals.css";
import Sidebar from "./components/Sidebar/Sidebar";
import GlobaStyleProvider from "./providers/GlobaStyleProvider";
import ContextProvider from "./providers/ContextProvider";



const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const { userId } = auth();

  return (
    <ClerkProvider>
      <html lang="en">
        <head>
          <link
            rel="stylesheet"
            href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css"
            integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA=="
            crossOrigin="anonymous"
            referrerPolicy="no-referrer"
          />
        </head>
        <body>
          <ContextProvider>
            <GlobaStyleProvider>
              {userId && <Sidebar />}
              <div className="w-full">{children}</div>
            </GlobaStyleProvider>
          </ContextProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}